version: '3'
services:
  app:
    build: .
    ports:
      - "9001:9001"
    volumes:
      - ./storage:/usr/src/app/storage
      - ./name:/usr/src/app/name
    environment:
      - NODE_ENV=production
