version: '3'
   services:
     app:
       build: .
       ports:
         - "9001:9001"
       volumes:
         - ./storage:/usr/src/app/storage
         - ./name:/usr/src/app/name
       environment:
         - NODE_ENV=production
       healthcheck:
         test: ["CMD", "curl", "-f", "http://localhost:9001/"]
         interval: 30s
         timeout: 10s
         retries: 3
         start_period: 40s
